INSERT INTO TB_PRODUCTS (ID, NAME, PRICE) VALUES (1, 'Apple', '2.0');
INSERT INTO TB_PRODUCTS (ID, NAME, PRICE) VALUES (2, 'Pear', '2.0');
INSERT INTO TB_PRODUCTS (ID, NAME, PRICE) VALUES (3, 'Orange', '2.0');